
name: test pushing docker hub pytest


on: 
  pull_request:
    types:
      - closed
    
env: 
  APP_VERSION: "1.0.0"
# A workflow run is made up  of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job

      # Checks-out your repository under $GITHUB_WORKSPACE,  so your job can access it
    steps:

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    - name: recuperation du repo 
      uses: actions/checkout@v3
    - name: version python
      uses: actions/setup-python
   
    - name: instal requirements
      run: pip install -r requierements.txt
    - name: run pytest 
      run: pytest



    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./


  Build:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
      - name: install QEMU
        uses: docker/setup-qemu-action@v1
      - name: instalation docker build X
        uses: docker/setup-buildx-action@v1
      - name: docker hub auth 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN }}

      - name: Build & push 
        uses: docker/build-push-action@v2 
        with:
          context: . 
          push: true 
          tags: ${{ secrets.LOGIN }}vanoud/python-pytest:${{ env.APP_VERSION }}